// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RXS48jtxH+KwUmx05rvDZy0CnrnTUgIN6dZO1cvHOoYZekMvjoIYuaFQb670GRrddI",
	"O06QIEiQix7dfHz1fV8Vi8/GRj/GQEGymT+bbNfksf58n1JM+mNMcaQkTPWxjQPp90DZJh6FYzDzNhjq",
	"u84sY/IoZm44yLdvTGdkO1L7SytKZtcZTznj6qsL7V8fpmZJHFZmt+tMosfCiQYz/8VMG+6H3+8684Ge",
	"7kgucQf0V7b7gJ4gLkHWBCPJ5YadEVxdzvtpO74+7wXQurvCm7Chcx+XZv7Ls/l9oqWZm9/NjkLMJhVm",
	"Uyy77mUwPFxC+jnwYyHg4RzXqRh//O6KGC+Q8mDud/c7fcxhGZvkQdBW3OSRnZkbHFkI/Z/yE65WlHqO",
	"ppsoNp/aM3h7t4CfCL3pTEk6aS0yzmezkzm77kUQbyGjHx3VybJGgZIpA2owWWIiwAwYgL60YRJhIB9D",
	"loRCsCSUkigDh0rBx5GCrvRtfwN5JMtLtli36oxjSyHT0Rvm7Yh2TfCmvzmDnOez2dPTU4/1dR/TajbN",
	"zbM/L969//Dp/R/e9Df9WryrhqHk88flJ0obtnQt7lkdMlMxWNwpZ3dTmKYzG0q5kfJNf9Pf6MpxpIAj",
	"m7n5tv+mohxR1tURMyVIf6yawc5p/StJSSEDOleZhGWKvjKUt1nIN6r1f8mUYK0kW0s5g8TP4QN6yDSA",
	"jWFgT0GKB8rSw49IlgJmEPJjTJBxxSKcIePIFDoIZCGtY7AlQyZ/MoAF0JP08JYCYQAUWCXc8ICAZVWo",
	"A7TAaIvjOrWHdyXhA0tJEAeO4GIi30FMARMBrUiAHE3oAtkObEm5ZE0IR1ZK7uG2cAbPICWNnDsYi9tw",
	"wKR7UYoadAfCwfJQgsAGE5cMv5YssYdFgDVaWCsIzJlgdCiEMLCV4pWORUspjQUHHjlbDivAIBrNMXbH",
	"q+LwEPm4xkSScE+ijgcfHWVhAvYjpYGVqb/xBn0LCB0/FvQwMCozCTM8amwbciwQYgCJSWJSSnhJYTjs",
	"3sNdQsoURGFSYH8EUFJA2ERXZESBDQUKqIAbufrhsSRdYxGOKy8pTawv0bLjfLZJ3UE/uqO+FnIc0JEK",
	"O3TKo6WEooHpdw+fSh4pDKwsO1TzDNHF1KkDM1lRN9coq1U06g42tGZbHIIWtjQUD44fKMUefozpgYEK",
	"Zx+HUxn0dTW2Q8uBsf8cPtFQdSgZlqTWc/Ehpjqc4tEvqUgqvgfNDI91uYl6zq4DKme50gQHV9SF6s0e",
	"7taYybmWFiOlaXoluYpLAksslh9Koxv3++i40/kbcpNwvKGUsDvfWrMEeOgOaRj4Yd3DzwIjOUdBKOup",
	"McZcSPNon0I9KBW4zwFNuT2T+5X2YVUeuwrkYIpQggVJnKUeShsWpB5+KNkSkNRaMBQ+5IDWiWzJUeIK",
	"p7l3P8GrVwpW69jiMwbwuNKQyU1q9fCX0qb66FS3ph6V5pwjlO5QegCL1RRpIydztrAna0wl5pCLahUV",
	"GDh0RyhT2gbOvAecFYNlKQMr1JwRiuxdNgnZdjojre7Xw92pMJW5CeOYSLj4k7rVTFO6E3dr4e0/6wGn",
	"DUM97BaDmZsfOAx6utRDIykBlHLtQM6PCsGVVn1YshNK8LA12giYuXkslLbHU17HmW5qGGtPIuTrCXTZ",
	"QbUHmBJu9X+WbT30tDWpzc05Ao9f2GsRL/6BknYziXJxUmGlepJ9BZNjz3IG6jdb0d29tj951MJS0b+5",
	"udn3PBRarzaObmobZr9mhfh8LezXGrnWxb0gYnfR/YwksAfTeqMlFif/FJ7XYLSW/srGJdCXUQurVuA2",
	"pjO5eI9pe6V9UGxjzFcajXeJUGrDFuhJx+47sdrV6AncsOsQbeaci080XJj17aBeNa0zpSzfx2H7b2Nh",
	"31Vf0nBHoh7DYdCvA2xz2iFLKrT7Fz3zm1b537HGheD1fe1GZ8887JpFHMmVy1d7rnMzh5WrNxZ4QC2z",
	"sblmcQu5aExXPHJbZzebvFrRFrdaQ8am7YRlqh/aPh/LBw8XSn+tlly/SV3Wku8uo1YgDcXw3yTk7UGM",
	"qsIWFrcK7/XrxLliBx0Xt187fr7f1nf/uF5LErv+j8n1f5vGLxRt6tchlDZ7mc5u8fsLeX9yrdW76e5+",
	"9/cAAAD//7FaKCRVEgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

