// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewTask struct {
	Title string `json:"title"`
	Notes string `json:"notes"`
}

type Task struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	Notes     string     `json:"notes"`
	Completed bool       `json:"completed"`
	Due       *time.Time `json:"due"`
}
