version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    volumes:
      - ./api:/app
      - ~/.aws:/root/.aws
    environment:
      - PORT=8080
      - GO_ENV=development
      - DB_USER=root
      - DB_NAME=api_dev
      - DB_PASSWORD=password
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_MAXOPENCONNECTION=100
      - DB_MAXIDLECONNECTION=10
      - DB_CONNECTIONMAXLIFETIMEHOUR=1
      - TEST_DB_NAME=api_test
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    build:
      context: ./mysql/docker
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/volume:/var/lib/mysql:delegated
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    platform: linux/x86_64

volumes:
  mysql_db:
    driver: local
